// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoupaDevAPI.Context;

#nullable disable

namespace PoupaDevAPI.Migrations
{
    [DbContext(typeof(PoupaDevAPIContext))]
    partial class PoupaDevAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PoupaDevAPI.Models.ContaObjetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("EstaDeletado")
                        .HasColumnType("bit");

                    b.Property<int>("ObjetivoFinanceiroId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoFinanceiroId")
                        .IsUnique();

                    b.ToTable("ContasObjetivos");
                });

            modelBuilder.Entity("PoupaDevAPI.Models.ObjetivoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaDeletado")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorObjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ObjetivosFinanceiros");
                });

            modelBuilder.Entity("PoupaDevAPI.Models.OperacaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstaDeletado")
                        .HasColumnType("bit");

                    b.Property<int>("ObjetivoFinanceiroId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoFinanceiroId");

                    b.ToTable("OperacoesFinanceiras");
                });

            modelBuilder.Entity("PoupaDevAPI.Models.ContaObjetivo", b =>
                {
                    b.HasOne("PoupaDevAPI.Models.ObjetivoFinanceiro", "ObjetivoFinanceiro")
                        .WithOne("Conta")
                        .HasForeignKey("PoupaDevAPI.Models.ContaObjetivo", "ObjetivoFinanceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetivoFinanceiro");
                });

            modelBuilder.Entity("PoupaDevAPI.Models.OperacaoFinanceira", b =>
                {
                    b.HasOne("PoupaDevAPI.Models.ObjetivoFinanceiro", null)
                        .WithMany("ListaOperacoes")
                        .HasForeignKey("ObjetivoFinanceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoupaDevAPI.Models.ObjetivoFinanceiro", b =>
                {
                    b.Navigation("Conta");

                    b.Navigation("ListaOperacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
